name: Hilightered
favicon: null
layout_spectrum: 0.9947003338020295
typography_spectrum: 0.27427611127495766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#faca36'
    - '#b38554'
    - '#64a54c'
    - '#317311'
  brandStrength: 0.2080399044789374
  lightness: 0.0625
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
